// <auto-generated />
using System;
using InvoiceWizard.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvoiceWizard.Backend.Migrations
{
    [DbContext(typeof(InvoiceWizardDbContext))]
    [Migration("20260318220658_AddInvoicePaymentDueDate")]
    partial class AddInvoicePaymentDueDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlatformAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.BankStatementImport", b =>
                {
                    b.Property<int>("BankStatementImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BankStatementImportId"));

                    b.Property<string>("AccountIban")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("BankStatementImportId");

                    b.HasIndex("TenantId");

                    b.ToTable("BankStatementImports");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.BankTransaction", b =>
                {
                    b.Property<int>("BankTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BankTransactionId"));

                    b.Property<string>("AccountIban")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("BalanceAfterBooking")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("BankStatementImportId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CounterpartyIban")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CounterpartyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("IgnoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IgnoredComment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("boolean");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("date");

                    b.HasKey("BankTransactionId");

                    b.HasIndex("BankStatementImportId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ContentHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "BookingDate", "Amount");

                    b.ToTable("BankTransactions");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.BankTransactionAssignment", b =>
                {
                    b.Property<int>("BankTransactionAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BankTransactionAssignmentId"));

                    b.Property<decimal>("AssignedAmount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BankTransactionId")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerInvoiceNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ManualCategory")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RevenueInvoiceId")
                        .HasColumnType("integer");

                    b.Property<int?>("SupplierInvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("BankTransactionAssignmentId");

                    b.HasIndex("BankTransactionId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RevenueInvoiceId");

                    b.HasIndex("SupplierInvoiceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "BankTransactionId");

                    b.HasIndex("TenantId", "CustomerInvoiceNumber");

                    b.HasIndex("TenantId", "RevenueInvoiceId");

                    b.HasIndex("TenantId", "SupplierInvoiceId");

                    b.ToTable("BankTransactionAssignments");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.CalendarEntry", b =>
                {
                    b.Property<int>("CalendarEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalendarEntryId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CalendarEntryId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CustomerId");

                    b.HasIndex("TenantId", "AppUserId", "EntryDate", "StartTime");

                    b.ToTable("CalendarEntries");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("DefaultMarkupPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("CustomerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CustomerNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceId"));

                    b.Property<string>("AccountingCategory")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("ApplySmallBusinessRegulation")
                        .HasColumnType("boolean");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DraftSavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasSupplierInvoice")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceDirection")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoiceStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("InvoiceTotalAmount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("OriginalPdfFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("date");

                    b.Property<string>("SourcePdfPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("StoredPdfContent")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("StoredPdfPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ContentHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "InvoiceDirection", "InvoiceNumber")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.InvoiceLine", b =>
                {
                    b.Property<int>("InvoiceLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceLineId"));

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GrossLineTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GrossListPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GrossUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MetalSurcharge")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceBasisQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InvoiceLineId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TenantId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.LicenseActivation", b =>
                {
                    b.Property<int>("LicenseActivationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LicenseActivationId"));

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool?>("IncludesMobileAccessOverride")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxCustomersOverride")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxProjectsOverride")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxUsersOverride")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceNet")
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("RenewsAutomatically")
                        .HasColumnType("boolean");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsedByAppUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LicenseActivationId");

                    b.HasIndex("ActivationCode")
                        .IsUnique();

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UsedByAppUserId");

                    b.ToTable("LicenseActivations");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.LineAllocation", b =>
                {
                    b.Property<int>("LineAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LineAllocationId"));

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("AllocatedQuantity")
                        .HasColumnType("numeric");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerInvoiceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CustomerInvoicedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CustomerUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExportedLineTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExportedMarkupPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExportedUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("InvoiceLineId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmallMaterial")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastExportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("RevenueInvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("LineAllocationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceLineId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RevenueInvoiceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "RevenueInvoiceId");

                    b.HasIndex("TenantId", "InvoiceLineId", "CustomerId", "ProjectId", "AllocatedQuantity");

                    b.ToTable("LineAllocations");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("ConnectionUserCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserEmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserHouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserParcelNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserPostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ConnectionUserSameAsCustomer")
                        .HasColumnType("boolean");

                    b.Property<string>("ConnectionUserStreet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerEmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerHouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerPostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PropertyOwnerSameAsCustomer")
                        .HasColumnType("boolean");

                    b.Property<string>("PropertyOwnerStreet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CustomerId", "Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.SubscriptionPlan", b =>
                {
                    b.Property<int>("SubscriptionPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionPlanId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IncludesMobileAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCustomers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxProjects")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("SubscriptionPlanId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantId"));

                    b.Property<string>("BankBic")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BankIban")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CompanyCity")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CompanyEmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CompanyHouseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CompanyStreet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NextCustomerNumber")
                        .HasColumnType("integer");

                    b.Property<int>("NextRevenueInvoiceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("TenantId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TenantLicense", b =>
                {
                    b.Property<int>("TenantLicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantLicenseId"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GraceUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IncludesMobileAccessOverride")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxCustomersOverride")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxProjectsOverride")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxUsersOverride")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextBillingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PriceNet")
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("RenewsAutomatically")
                        .HasColumnType("boolean");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantLicenseId");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("TenantId", "IsActive");

                    b.ToTable("TenantLicenses");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TenantSoneparConnection", b =>
                {
                    b.Property<int>("TenantSoneparConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantSoneparConnectionId"));

                    b.Property<string>("ClientIdCipherText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerNumberCipherText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("LastValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OmdVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OpenMasterDataBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordCipherText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("TokenUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TenantSoneparConnectionId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantSoneparConnections");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoAttachment", b =>
                {
                    b.Property<int>("TodoAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoAttachmentId"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("TodoListId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TodoAttachmentId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TodoListId");

                    b.ToTable("TodoAttachments");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoItem", b =>
                {
                    b.Property<int>("TodoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentTodoItemId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TodoListId")
                        .HasColumnType("integer");

                    b.HasKey("TodoItemId");

                    b.HasIndex("ParentTodoItemId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TodoListId");

                    b.HasIndex("TenantId", "TodoListId", "ParentTodoItemId", "SortOrder");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoList", b =>
                {
                    b.Property<int>("TodoListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoListId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TodoListId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CustomerId", "ProjectId", "UpdatedAt");

                    b.ToTable("TodoLists");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.UserTenantMembership", b =>
                {
                    b.Property<int>("UserTenantMembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTenantMembershipId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("UserTenantMembershipId");

                    b.HasIndex("TenantId");

                    b.HasIndex("AppUserId", "TenantId")
                        .IsUnique();

                    b.ToTable("UserTenantMemberships");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.WorkTimeEntry", b =>
                {
                    b.Property<int>("WorkTimeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkTimeEntryId"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerInvoiceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CustomerInvoicedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<decimal>("ExportedLineTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExportedUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsClockActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastExportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PauseStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("RevenueInvoiceId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TravelKilometers")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TravelRatePerKilometer")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("WorkTimeEntryId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RevenueInvoiceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "RevenueInvoiceId");

                    b.HasIndex("TenantId", "AppUserId", "IsClockActive");

                    b.HasIndex("TenantId", "CustomerId", "ProjectId", "WorkDate", "StartTime", "EndTime");

                    b.ToTable("WorkTimeEntries");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.BankStatementImport", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.BankTransaction", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.BankStatementImport", "BankStatementImport")
                        .WithMany("Transactions")
                        .HasForeignKey("BankStatementImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BankStatementImport");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.BankTransactionAssignment", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.BankTransaction", "BankTransaction")
                        .WithMany("Assignments")
                        .HasForeignKey("BankTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceWizard.Backend.Domain.Invoice", "RevenueInvoice")
                        .WithMany()
                        .HasForeignKey("RevenueInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceWizard.Backend.Domain.Invoice", "SupplierInvoice")
                        .WithMany()
                        .HasForeignKey("SupplierInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BankTransaction");

                    b.Navigation("Customer");

                    b.Navigation("RevenueInvoice");

                    b.Navigation("SupplierInvoice");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.CalendarEntry", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Customer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Customer", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Invoice", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.InvoiceLine", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.LicenseActivation", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.AppUser", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("LicenseActivations")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.AppUser", "UsedByAppUser")
                        .WithMany()
                        .HasForeignKey("UsedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("UsedByAppUser");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.LineAllocation", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany("Allocations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.InvoiceLine", "InvoiceLine")
                        .WithMany("Allocations")
                        .HasForeignKey("InvoiceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Project", "Project")
                        .WithMany("Allocations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceWizard.Backend.Domain.Invoice", "RevenueInvoice")
                        .WithMany()
                        .HasForeignKey("RevenueInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("InvoiceLine");

                    b.Navigation("Project");

                    b.Navigation("RevenueInvoice");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Project", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TenantLicense", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Licenses")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany("Licenses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TenantSoneparConnection", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoAttachment", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.TodoList", "TodoList")
                        .WithMany("Attachments")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoItem", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.TodoItem", "ParentTodoItem")
                        .WithMany("Children")
                        .HasForeignKey("ParentTodoItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.TodoList", "TodoList")
                        .WithMany("Items")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTodoItem");

                    b.Navigation("Tenant");

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoList", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany("TodoLists")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Project", "Project")
                        .WithMany("TodoLists")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Project");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.UserTenantMembership", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.AppUser", "AppUser")
                        .WithMany("Memberships")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.WorkTimeEntry", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.AppUser", "AppUser")
                        .WithMany("WorkTimeEntries")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany("WorkTimeEntries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Project", "Project")
                        .WithMany("WorkTimeEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceWizard.Backend.Domain.Invoice", "RevenueInvoice")
                        .WithMany()
                        .HasForeignKey("RevenueInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceWizard.Backend.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Customer");

                    b.Navigation("Project");

                    b.Navigation("RevenueInvoice");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.AppUser", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("WorkTimeEntries");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.BankStatementImport", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.BankTransaction", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Customer", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Projects");

                    b.Navigation("TodoLists");

                    b.Navigation("WorkTimeEntries");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.InvoiceLine", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Project", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("TodoLists");

                    b.Navigation("WorkTimeEntries");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.SubscriptionPlan", b =>
                {
                    b.Navigation("LicenseActivations");

                    b.Navigation("Licenses");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Tenant", b =>
                {
                    b.Navigation("Licenses");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoList", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
