// <auto-generated />
using System;
using InvoiceWizard.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvoiceWizard.Backend.Migrations
{
    [DbContext(typeof(InvoiceWizardDbContext))]
    [Migration("20260312062932_AddConnectionUserParcelNumber")]
    partial class AddConnectionUserParcelNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DefaultMarkupPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceId"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourcePdfPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.InvoiceLine", b =>
                {
                    b.Property<int>("InvoiceLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceLineId"));

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GrossListPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceBasisQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InvoiceLineId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.LineAllocation", b =>
                {
                    b.Property<int>("LineAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LineAllocationId"));

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("AllocatedQuantity")
                        .HasColumnType("numeric");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerInvoiceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CustomerInvoicedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CustomerUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExportedLineTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExportedMarkupPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExportedUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("InvoiceLineId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmallMaterial")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastExportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("LineAllocationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("InvoiceLineId", "CustomerId", "ProjectId", "AllocatedQuantity");

                    b.ToTable("LineAllocations");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("ConnectionUserCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserEmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserHouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserParcelNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionUserPostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ConnectionUserSameAsCustomer")
                        .HasColumnType("boolean");

                    b.Property<string>("ConnectionUserStreet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerEmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerHouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyOwnerPostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PropertyOwnerSameAsCustomer")
                        .HasColumnType("boolean");

                    b.Property<string>("PropertyOwnerStreet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.HasIndex("CustomerId", "Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoAttachment", b =>
                {
                    b.Property<int>("TodoAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoAttachmentId"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("TodoListId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TodoAttachmentId");

                    b.HasIndex("TodoListId");

                    b.ToTable("TodoAttachments");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoItem", b =>
                {
                    b.Property<int>("TodoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentTodoItemId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TodoListId")
                        .HasColumnType("integer");

                    b.HasKey("TodoItemId");

                    b.HasIndex("ParentTodoItemId");

                    b.HasIndex("TodoListId", "ParentTodoItemId", "SortOrder");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoList", b =>
                {
                    b.Property<int>("TodoListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoListId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TodoListId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("CustomerId", "ProjectId", "UpdatedAt");

                    b.ToTable("TodoLists");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.WorkTimeEntry", b =>
                {
                    b.Property<int>("WorkTimeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkTimeEntryId"));

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerInvoiceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CustomerInvoicedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<decimal>("ExportedLineTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExportedUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastExportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<decimal>("TravelKilometers")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TravelRatePerKilometer")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("WorkTimeEntryId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("CustomerId", "ProjectId", "WorkDate", "StartTime", "EndTime");

                    b.ToTable("WorkTimeEntries");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.InvoiceLine", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.LineAllocation", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany("Allocations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.InvoiceLine", "InvoiceLine")
                        .WithMany("Allocations")
                        .HasForeignKey("InvoiceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Project", "Project")
                        .WithMany("Allocations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("InvoiceLine");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Project", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoAttachment", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.TodoList", "TodoList")
                        .WithMany("Attachments")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoItem", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.TodoItem", "ParentTodoItem")
                        .WithMany("Children")
                        .HasForeignKey("ParentTodoItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceWizard.Backend.Domain.TodoList", "TodoList")
                        .WithMany("Items")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTodoItem");

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoList", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany("TodoLists")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Project", "Project")
                        .WithMany("TodoLists")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.WorkTimeEntry", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany("WorkTimeEntries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Project", "Project")
                        .WithMany("WorkTimeEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Customer", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Projects");

                    b.Navigation("TodoLists");

                    b.Navigation("WorkTimeEntries");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.InvoiceLine", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Project", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("TodoLists");

                    b.Navigation("WorkTimeEntries");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.TodoList", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
