// <auto-generated />
using System;
using InvoiceWizard.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvoiceWizard.Backend.Migrations
{
    [DbContext(typeof(InvoiceWizardDbContext))]
    partial class InvoiceWizardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<decimal>("DefaultMarkupPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceId"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourcePdfPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.InvoiceLine", b =>
                {
                    b.Property<int>("InvoiceLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceLineId"));

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GrossListPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceBasisQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InvoiceLineId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.LineAllocation", b =>
                {
                    b.Property<int>("LineAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LineAllocationId"));

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("AllocatedQuantity")
                        .HasColumnType("numeric");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerInvoiceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CustomerInvoicedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CustomerUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExportedLineTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExportedMarkupPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExportedUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("InvoiceLineId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmallMaterial")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastExportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("LineAllocationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("InvoiceLineId", "CustomerId", "ProjectId", "AllocatedQuantity");

                    b.ToTable("LineAllocations");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.HasIndex("CustomerId", "Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.WorkTimeEntry", b =>
                {
                    b.Property<int>("WorkTimeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkTimeEntryId"));

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerInvoiceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CustomerInvoicedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<decimal>("ExportedLineTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExportedUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastExportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("WorkTimeEntryId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("CustomerId", "ProjectId", "WorkDate", "StartTime", "EndTime");

                    b.ToTable("WorkTimeEntries");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.InvoiceLine", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.LineAllocation", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany("Allocations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.InvoiceLine", "InvoiceLine")
                        .WithMany("Allocations")
                        .HasForeignKey("InvoiceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Project", "Project")
                        .WithMany("Allocations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("InvoiceLine");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Project", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.WorkTimeEntry", b =>
                {
                    b.HasOne("InvoiceWizard.Backend.Domain.Customer", "Customer")
                        .WithMany("WorkTimeEntries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceWizard.Backend.Domain.Project", "Project")
                        .WithMany("WorkTimeEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Customer", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Projects");

                    b.Navigation("WorkTimeEntries");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.InvoiceLine", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("InvoiceWizard.Backend.Domain.Project", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("WorkTimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}


